###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]

class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client


    
    async def ExtractChunk(
        self,
        chunk: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DynamicContainer:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractChunk",
        {
          "chunk": chunk,"context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.DynamicContainer, raw.cast_to(types, types, partial_types, False))
    
    async def InferRelationship(
        self,
        rel_type: str,source_type: str,target_type: str,source_entities: str,target_entities: str,existing_rels: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.RelationshipInference]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "InferRelationship",
        {
          "rel_type": rel_type,"source_type": source_type,"target_type": target_type,"source_entities": source_entities,"target_entities": target_entities,"existing_rels": existing_rels,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.RelationshipInference], raw.cast_to(types, types, partial_types, False))
    
    async def ResolveEntities(
        self,
        entity_type: str,node_dicts_str: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolvedEntities]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ResolveEntities",
        {
          "entity_type": entity_type,"node_dicts_str": node_dicts_str,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.ResolvedEntities], raw.cast_to(types, types, partial_types, False))
    
    async def StandardiseProperties(
        self,
        entity_group_type: str,entities_json: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.StandardisedProperties]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "StandardiseProperties",
        {
          "entity_group_type": entity_group_type,"entities_json": entities_json,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.StandardisedProperties], raw.cast_to(types, types, partial_types, False))
    


class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def ExtractChunk(
        self,
        chunk: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.DynamicContainer, types.DynamicContainer]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractChunk",
        {
          "chunk": chunk,
          "context": context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.DynamicContainer, types.DynamicContainer](
        raw,
        lambda x: cast(partial_types.DynamicContainer, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.DynamicContainer, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def InferRelationship(
        self,
        rel_type: str,source_type: str,target_type: str,source_entities: str,target_entities: str,existing_rels: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.RelationshipInference], List[types.RelationshipInference]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "InferRelationship",
        {
          "rel_type": rel_type,
          "source_type": source_type,
          "target_type": target_type,
          "source_entities": source_entities,
          "target_entities": target_entities,
          "existing_rels": existing_rels,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[List[partial_types.RelationshipInference], List[types.RelationshipInference]](
        raw,
        lambda x: cast(List[partial_types.RelationshipInference], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.RelationshipInference], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ResolveEntities(
        self,
        entity_type: str,node_dicts_str: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.ResolvedEntities], List[types.ResolvedEntities]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ResolveEntities",
        {
          "entity_type": entity_type,
          "node_dicts_str": node_dicts_str,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[List[partial_types.ResolvedEntities], List[types.ResolvedEntities]](
        raw,
        lambda x: cast(List[partial_types.ResolvedEntities], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.ResolvedEntities], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def StandardiseProperties(
        self,
        entity_group_type: str,entities_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.StandardisedProperties], List[types.StandardisedProperties]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "StandardiseProperties",
        {
          "entity_group_type": entity_group_type,
          "entities_json": entities_json,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[List[partial_types.StandardisedProperties], List[types.StandardisedProperties]](
        raw,
        lambda x: cast(List[partial_types.StandardisedProperties], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.StandardisedProperties], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    

b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]