###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]
    collector: NotRequired[Union[baml_py.baml_py.Collector, List[baml_py.baml_py.Collector]]]
class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client


    
    async def AnalyzeConflict(
        self,
        entity_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeConflict",
        {
          "entity_type": entity_type,"property_name": property_name,"staging_value": staging_value,"production_value": production_value,"value_type": value_type,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeConflictGroup(
        self,
        entity_type: str,property_name: str,value_type: str,conflict_count: int,sample_conflicts: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictGroupAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeConflictGroup",
        {
          "entity_type": entity_type,"property_name": property_name,"value_type": value_type,"conflict_count": conflict_count,"sample_conflicts": sample_conflicts,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictGroupAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeDuplicateEntityConflict(
        self,
        entity_type: str,staging_entity_id: str,production_entity_ids: str,similarity_scores: str,entity_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeDuplicateEntityConflict",
        {
          "entity_type": entity_type,"staging_entity_id": staging_entity_id,"production_entity_ids": production_entity_ids,"similarity_scores": similarity_scores,"entity_properties": entity_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeEntityMatchConflict(
        self,
        entity_type: str,staging_entity_id: str,production_entity_id: str,match_confidence: float,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeEntityMatchConflict",
        {
          "entity_type": entity_type,"staging_entity_id": staging_entity_id,"production_entity_id": production_entity_id,"match_confidence": match_confidence,"staging_properties": staging_properties,"production_properties": production_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeEntityMatchConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeEntityMatchConflictWithOntology",
        {
          "conflict": conflict,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeEntityMatchResolutionOption(
        self,
        entity_type: str,resolution_option: str,staging_entity_id: str,production_entity_id: str,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeEntityMatchResolutionOption",
        {
          "entity_type": entity_type,"resolution_option": resolution_option,"staging_entity_id": staging_entity_id,"production_entity_id": production_entity_id,"staging_properties": staging_properties,"production_properties": production_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeEntityMatchWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeEntityMatchWithOntology",
        {
          "conflict": conflict,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeEntitySimilarity(
        self,
        entity_type: str,staging_properties: str,production_properties: str,domain_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.EntitySimilarityAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeEntitySimilarity",
        {
          "entity_type": entity_type,"staging_properties": staging_properties,"production_properties": production_properties,"domain_context": domain_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.EntitySimilarityAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeGenericConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeGenericConflictWithOntology",
        {
          "conflict": conflict,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeMissingRelationshipConflict(
        self,
        relationship_type: str,source_entity_type: str,target_entity_type: str,source_entity_id: str,target_entity_id: str,exists_in: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RelationshipConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeMissingRelationshipConflict",
        {
          "relationship_type": relationship_type,"source_entity_type": source_entity_type,"target_entity_type": target_entity_type,"source_entity_id": source_entity_id,"target_entity_id": target_entity_id,"exists_in": exists_in,"graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.RelationshipConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzePropertyConflict(
        self,
        entity_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,historical_resolutions: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PropertyConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzePropertyConflict",
        {
          "entity_type": entity_type,"property_name": property_name,"staging_value": staging_value,"production_value": production_value,"value_type": value_type,"historical_resolutions": historical_resolutions,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.PropertyConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzePropertyConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzePropertyConflictWithOntology",
        {
          "conflict": conflict,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeRelationshipConflict(
        self,
        relationship_type: str,conflict_type: str,staging_details: str,production_details: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RelationshipConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeRelationshipConflict",
        {
          "relationship_type": relationship_type,"conflict_type": conflict_type,"staging_details": staging_details,"production_details": production_details,"graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.RelationshipConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeRelationshipConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeRelationshipConflictWithOntology",
        {
          "conflict": conflict,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeRelationshipDirectionConflict(
        self,
        relationship_type: str,staging_source_id: str,staging_target_id: str,production_source_id: str,production_target_id: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RelationshipConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeRelationshipDirectionConflict",
        {
          "relationship_type": relationship_type,"staging_source_id": staging_source_id,"staging_target_id": staging_target_id,"production_source_id": production_source_id,"production_target_id": production_target_id,"graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.RelationshipConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeRelationshipPropertyConflict(
        self,
        relationship_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RelationshipConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeRelationshipPropertyConflict",
        {
          "relationship_type": relationship_type,"property_name": property_name,"staging_value": staging_value,"production_value": production_value,"value_type": value_type,"graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.RelationshipConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeRelationshipTypeConflict(
        self,
        staging_relationship_type: str,production_relationship_type: str,source_entity_type: str,target_entity_type: str,source_entity_id: str,target_entity_id: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RelationshipConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeRelationshipTypeConflict",
        {
          "staging_relationship_type": staging_relationship_type,"production_relationship_type": production_relationship_type,"source_entity_type": source_entity_type,"target_entity_type": target_entity_type,"source_entity_id": source_entity_id,"target_entity_id": target_entity_id,"graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.RelationshipConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeSchemaConflict(
        self,
        entity_type: str,conflict_description: str,staging_schema: str,production_schema: str,affected_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeSchemaConflict",
        {
          "entity_type": entity_type,"conflict_description": conflict_description,"staging_schema": staging_schema,"production_schema": production_schema,"affected_properties": affected_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AnalyzeSchemaConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AnalyzeSchemaConflictWithOntology",
        {
          "conflict": conflict,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def AssessResolutionComplexity(
        self,
        conflict_type: str,classification: str,resolution_option: str,
        baml_options: BamlCallOptions = {},
    ) -> float:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "AssessResolutionComplexity",
        {
          "conflict_type": conflict_type,"classification": classification,"resolution_option": resolution_option,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(float, raw.cast_to(types, types, partial_types, False))
    
    async def BatchAnalyzeConflicts(
        self,
        conflict_type: str,entity_type: str,conflict_summaries: str,sample_conflicts: str,total_count: int,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictGroupAnalysis:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "BatchAnalyzeConflicts",
        {
          "conflict_type": conflict_type,"entity_type": entity_type,"conflict_summaries": conflict_summaries,"sample_conflicts": sample_conflicts,"total_count": total_count,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictGroupAnalysis, raw.cast_to(types, types, partial_types, False))
    
    async def ClassifyConflict(
        self,
        analysis: str,conflict_type: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ConflictClassification:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "ClassifyConflict",
        {
          "analysis": analysis,"conflict_type": conflict_type,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ConflictClassification, raw.cast_to(types, types, partial_types, False))
    
    async def ExtractChunk(
        self,
        chunk: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DynamicContainer:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "ExtractChunk",
        {
          "chunk": chunk,"context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.DynamicContainer, raw.cast_to(types, types, partial_types, False))
    
    async def GenerateEntityMatchResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ResolutionOptions:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "GenerateEntityMatchResolutionOptions",
        {
          "conflict": conflict,"analysis": analysis,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ResolutionOptions, raw.cast_to(types, types, partial_types, False))
    
    async def GenerateEntityMatchResolutionOptionsFromStagingAndProd(
        self,
        conflict_analysis: str,entity_type: str,staging_entity_id: str,production_entity_id: str,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolutionOption]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "GenerateEntityMatchResolutionOptionsFromStagingAndProd",
        {
          "conflict_analysis": conflict_analysis,"entity_type": entity_type,"staging_entity_id": staging_entity_id,"production_entity_id": production_entity_id,"staging_properties": staging_properties,"production_properties": production_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(List[types.ResolutionOption], raw.cast_to(types, types, partial_types, False))
    
    async def GenerateGenericResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ResolutionOptions:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "GenerateGenericResolutionOptions",
        {
          "conflict": conflict,"analysis": analysis,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ResolutionOptions, raw.cast_to(types, types, partial_types, False))
    
    async def GeneratePropertyResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ResolutionOptions:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "GeneratePropertyResolutionOptions",
        {
          "conflict": conflict,"analysis": analysis,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ResolutionOptions, raw.cast_to(types, types, partial_types, False))
    
    async def GenerateRelationshipResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.ResolutionOptions:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "GenerateRelationshipResolutionOptions",
        {
          "conflict": conflict,"analysis": analysis,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ResolutionOptions, raw.cast_to(types, types, partial_types, False))
    
    async def GenerateResolutionOptions(
        self,
        conflict_analysis: str,classification: str,staging_element: str,prod_element: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolutionOption]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "GenerateResolutionOptions",
        {
          "conflict_analysis": conflict_analysis,"classification": classification,"staging_element": staging_element,"prod_element": prod_element,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(List[types.ResolutionOption], raw.cast_to(types, types, partial_types, False))
    
    async def GenerateSchemaConflictResolutionOptions(
        self,
        conflict_analysis: str,entity_type: str,staging_schema: str,production_schema: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolutionOption]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "GenerateSchemaConflictResolutionOptions",
        {
          "conflict_analysis": conflict_analysis,"entity_type": entity_type,"staging_schema": staging_schema,"production_schema": production_schema,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(List[types.ResolutionOption], raw.cast_to(types, types, partial_types, False))
    
    async def InferRelationship(
        self,
        rel_type: str,source_type: str,target_type: str,source_entities: str,target_entities: str,existing_rels: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.RelationshipInference]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "InferRelationship",
        {
          "rel_type": rel_type,"source_type": source_type,"target_type": target_type,"source_entities": source_entities,"target_entities": target_entities,"existing_rels": existing_rels,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(List[types.RelationshipInference], raw.cast_to(types, types, partial_types, False))
    
    async def ResolveEntities(
        self,
        entity_type: str,node_dicts_str: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.ResolvedEntities]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "ResolveEntities",
        {
          "entity_type": entity_type,"node_dicts_str": node_dicts_str,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(List[types.ResolvedEntities], raw.cast_to(types, types, partial_types, False))
    
    async def SelectBestResolution(
        self,
        conflict: types.JsonObject,options: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> types.SelectedResolution:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "SelectBestResolution",
        {
          "conflict": conflict,"options": options,"ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SelectedResolution, raw.cast_to(types, types, partial_types, False))
    
    async def StandardiseProperties(
        self,
        entity_group_type: str,entities_json: str,
        baml_options: BamlCallOptions = {},
    ) -> List[types.StandardisedProperties]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "StandardiseProperties",
        {
          "entity_group_type": entity_group_type,"entities_json": entities_json,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(List[types.StandardisedProperties], raw.cast_to(types, types, partial_types, False))
    


class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def AnalyzeConflict(
        self,
        entity_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeConflict",
        {
          "entity_type": entity_type,
          "property_name": property_name,
          "staging_value": staging_value,
          "production_value": production_value,
          "value_type": value_type,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeConflictGroup(
        self,
        entity_type: str,property_name: str,value_type: str,conflict_count: int,sample_conflicts: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictGroupAnalysis, types.ConflictGroupAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeConflictGroup",
        {
          "entity_type": entity_type,
          "property_name": property_name,
          "value_type": value_type,
          "conflict_count": conflict_count,
          "sample_conflicts": sample_conflicts,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictGroupAnalysis, types.ConflictGroupAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictGroupAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictGroupAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeDuplicateEntityConflict(
        self,
        entity_type: str,staging_entity_id: str,production_entity_ids: str,similarity_scores: str,entity_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeDuplicateEntityConflict",
        {
          "entity_type": entity_type,
          "staging_entity_id": staging_entity_id,
          "production_entity_ids": production_entity_ids,
          "similarity_scores": similarity_scores,
          "entity_properties": entity_properties,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeEntityMatchConflict(
        self,
        entity_type: str,staging_entity_id: str,production_entity_id: str,match_confidence: float,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeEntityMatchConflict",
        {
          "entity_type": entity_type,
          "staging_entity_id": staging_entity_id,
          "production_entity_id": production_entity_id,
          "match_confidence": match_confidence,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeEntityMatchConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeEntityMatchConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeEntityMatchResolutionOption(
        self,
        entity_type: str,resolution_option: str,staging_entity_id: str,production_entity_id: str,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeEntityMatchResolutionOption",
        {
          "entity_type": entity_type,
          "resolution_option": resolution_option,
          "staging_entity_id": staging_entity_id,
          "production_entity_id": production_entity_id,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeEntityMatchWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeEntityMatchWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeEntitySimilarity(
        self,
        entity_type: str,staging_properties: str,production_properties: str,domain_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.EntitySimilarityAnalysis, types.EntitySimilarityAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeEntitySimilarity",
        {
          "entity_type": entity_type,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
          "domain_context": domain_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.EntitySimilarityAnalysis, types.EntitySimilarityAnalysis](
        raw,
        lambda x: cast(partial_types.EntitySimilarityAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.EntitySimilarityAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeGenericConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeGenericConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeMissingRelationshipConflict(
        self,
        relationship_type: str,source_entity_type: str,target_entity_type: str,source_entity_id: str,target_entity_id: str,exists_in: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeMissingRelationshipConflict",
        {
          "relationship_type": relationship_type,
          "source_entity_type": source_entity_type,
          "target_entity_type": target_entity_type,
          "source_entity_id": source_entity_id,
          "target_entity_id": target_entity_id,
          "exists_in": exists_in,
          "graph_context": graph_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis](
        raw,
        lambda x: cast(partial_types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzePropertyConflict(
        self,
        entity_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,historical_resolutions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.PropertyConflictAnalysis, types.PropertyConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzePropertyConflict",
        {
          "entity_type": entity_type,
          "property_name": property_name,
          "staging_value": staging_value,
          "production_value": production_value,
          "value_type": value_type,
          "historical_resolutions": historical_resolutions,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.PropertyConflictAnalysis, types.PropertyConflictAnalysis](
        raw,
        lambda x: cast(partial_types.PropertyConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.PropertyConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzePropertyConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzePropertyConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeRelationshipConflict(
        self,
        relationship_type: str,conflict_type: str,staging_details: str,production_details: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeRelationshipConflict",
        {
          "relationship_type": relationship_type,
          "conflict_type": conflict_type,
          "staging_details": staging_details,
          "production_details": production_details,
          "graph_context": graph_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis](
        raw,
        lambda x: cast(partial_types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeRelationshipConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeRelationshipConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeRelationshipDirectionConflict(
        self,
        relationship_type: str,staging_source_id: str,staging_target_id: str,production_source_id: str,production_target_id: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeRelationshipDirectionConflict",
        {
          "relationship_type": relationship_type,
          "staging_source_id": staging_source_id,
          "staging_target_id": staging_target_id,
          "production_source_id": production_source_id,
          "production_target_id": production_target_id,
          "graph_context": graph_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis](
        raw,
        lambda x: cast(partial_types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeRelationshipPropertyConflict(
        self,
        relationship_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeRelationshipPropertyConflict",
        {
          "relationship_type": relationship_type,
          "property_name": property_name,
          "staging_value": staging_value,
          "production_value": production_value,
          "value_type": value_type,
          "graph_context": graph_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis](
        raw,
        lambda x: cast(partial_types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeRelationshipTypeConflict(
        self,
        staging_relationship_type: str,production_relationship_type: str,source_entity_type: str,target_entity_type: str,source_entity_id: str,target_entity_id: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeRelationshipTypeConflict",
        {
          "staging_relationship_type": staging_relationship_type,
          "production_relationship_type": production_relationship_type,
          "source_entity_type": source_entity_type,
          "target_entity_type": target_entity_type,
          "source_entity_id": source_entity_id,
          "target_entity_id": target_entity_id,
          "graph_context": graph_context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.RelationshipConflictAnalysis, types.RelationshipConflictAnalysis](
        raw,
        lambda x: cast(partial_types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RelationshipConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeSchemaConflict(
        self,
        entity_type: str,conflict_description: str,staging_schema: str,production_schema: str,affected_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeSchemaConflict",
        {
          "entity_type": entity_type,
          "conflict_description": conflict_description,
          "staging_schema": staging_schema,
          "production_schema": production_schema,
          "affected_properties": affected_properties,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AnalyzeSchemaConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AnalyzeSchemaConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictAnalysis, types.ConflictAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def AssessResolutionComplexity(
        self,
        conflict_type: str,classification: str,resolution_option: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[Optional[float], float]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "AssessResolutionComplexity",
        {
          "conflict_type": conflict_type,
          "classification": classification,
          "resolution_option": resolution_option,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[Optional[float], float](
        raw,
        lambda x: cast(Optional[float], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(float, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def BatchAnalyzeConflicts(
        self,
        conflict_type: str,entity_type: str,conflict_summaries: str,sample_conflicts: str,total_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictGroupAnalysis, types.ConflictGroupAnalysis]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "BatchAnalyzeConflicts",
        {
          "conflict_type": conflict_type,
          "entity_type": entity_type,
          "conflict_summaries": conflict_summaries,
          "sample_conflicts": sample_conflicts,
          "total_count": total_count,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictGroupAnalysis, types.ConflictGroupAnalysis](
        raw,
        lambda x: cast(partial_types.ConflictGroupAnalysis, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictGroupAnalysis, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ClassifyConflict(
        self,
        analysis: str,conflict_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ConflictClassification, types.ConflictClassification]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "ClassifyConflict",
        {
          "analysis": analysis,
          "conflict_type": conflict_type,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ConflictClassification, types.ConflictClassification](
        raw,
        lambda x: cast(partial_types.ConflictClassification, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ConflictClassification, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ExtractChunk(
        self,
        chunk: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.DynamicContainer, types.DynamicContainer]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "ExtractChunk",
        {
          "chunk": chunk,
          "context": context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.DynamicContainer, types.DynamicContainer](
        raw,
        lambda x: cast(partial_types.DynamicContainer, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.DynamicContainer, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateEntityMatchResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ResolutionOptions, types.ResolutionOptions]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "GenerateEntityMatchResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ResolutionOptions, types.ResolutionOptions](
        raw,
        lambda x: cast(partial_types.ResolutionOptions, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ResolutionOptions, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateEntityMatchResolutionOptionsFromStagingAndProd(
        self,
        conflict_analysis: str,entity_type: str,staging_entity_id: str,production_entity_id: str,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.ResolutionOption], List[types.ResolutionOption]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "GenerateEntityMatchResolutionOptionsFromStagingAndProd",
        {
          "conflict_analysis": conflict_analysis,
          "entity_type": entity_type,
          "staging_entity_id": staging_entity_id,
          "production_entity_id": production_entity_id,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[List[partial_types.ResolutionOption], List[types.ResolutionOption]](
        raw,
        lambda x: cast(List[partial_types.ResolutionOption], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.ResolutionOption], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateGenericResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ResolutionOptions, types.ResolutionOptions]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "GenerateGenericResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ResolutionOptions, types.ResolutionOptions](
        raw,
        lambda x: cast(partial_types.ResolutionOptions, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ResolutionOptions, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GeneratePropertyResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ResolutionOptions, types.ResolutionOptions]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "GeneratePropertyResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ResolutionOptions, types.ResolutionOptions](
        raw,
        lambda x: cast(partial_types.ResolutionOptions, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ResolutionOptions, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateRelationshipResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ResolutionOptions, types.ResolutionOptions]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "GenerateRelationshipResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ResolutionOptions, types.ResolutionOptions](
        raw,
        lambda x: cast(partial_types.ResolutionOptions, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ResolutionOptions, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateResolutionOptions(
        self,
        conflict_analysis: str,classification: str,staging_element: str,prod_element: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.ResolutionOption], List[types.ResolutionOption]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "GenerateResolutionOptions",
        {
          "conflict_analysis": conflict_analysis,
          "classification": classification,
          "staging_element": staging_element,
          "prod_element": prod_element,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[List[partial_types.ResolutionOption], List[types.ResolutionOption]](
        raw,
        lambda x: cast(List[partial_types.ResolutionOption], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.ResolutionOption], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateSchemaConflictResolutionOptions(
        self,
        conflict_analysis: str,entity_type: str,staging_schema: str,production_schema: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.ResolutionOption], List[types.ResolutionOption]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "GenerateSchemaConflictResolutionOptions",
        {
          "conflict_analysis": conflict_analysis,
          "entity_type": entity_type,
          "staging_schema": staging_schema,
          "production_schema": production_schema,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[List[partial_types.ResolutionOption], List[types.ResolutionOption]](
        raw,
        lambda x: cast(List[partial_types.ResolutionOption], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.ResolutionOption], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def InferRelationship(
        self,
        rel_type: str,source_type: str,target_type: str,source_entities: str,target_entities: str,existing_rels: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.RelationshipInference], List[types.RelationshipInference]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "InferRelationship",
        {
          "rel_type": rel_type,
          "source_type": source_type,
          "target_type": target_type,
          "source_entities": source_entities,
          "target_entities": target_entities,
          "existing_rels": existing_rels,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[List[partial_types.RelationshipInference], List[types.RelationshipInference]](
        raw,
        lambda x: cast(List[partial_types.RelationshipInference], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.RelationshipInference], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ResolveEntities(
        self,
        entity_type: str,node_dicts_str: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.ResolvedEntities], List[types.ResolvedEntities]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "ResolveEntities",
        {
          "entity_type": entity_type,
          "node_dicts_str": node_dicts_str,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[List[partial_types.ResolvedEntities], List[types.ResolvedEntities]](
        raw,
        lambda x: cast(List[partial_types.ResolvedEntities], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.ResolvedEntities], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SelectBestResolution(
        self,
        conflict: types.JsonObject,options: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.SelectedResolution, types.SelectedResolution]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "SelectBestResolution",
        {
          "conflict": conflict,
          "options": options,
          "ontology": ontology,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.SelectedResolution, types.SelectedResolution](
        raw,
        lambda x: cast(partial_types.SelectedResolution, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SelectedResolution, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def StandardiseProperties(
        self,
        entity_group_type: str,entities_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.StandardisedProperties], List[types.StandardisedProperties]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "StandardiseProperties",
        {
          "entity_group_type": entity_group_type,
          "entities_json": entities_json,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[List[partial_types.StandardisedProperties], List[types.StandardisedProperties]](
        raw,
        lambda x: cast(List[partial_types.StandardisedProperties], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.StandardisedProperties], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    

b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]