###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class DynamicContainer(BaseModel):
    model_config = ConfigDict(extra='allow')

class RelationshipInference(BaseModel):
    id: Optional[str] = None
    type: Optional[str] = None
    source_id: Optional[str] = None
    target_id: Optional[str] = None
    source_type: Optional[str] = None
    target_type: Optional[str] = None
    properties: Dict[str, Optional[str]]
    confidence_score: Optional[float] = None

class ResolvedEntities(BaseModel):
    matching_ids: List[str]
    confidence_scores: Optional[float] = None
    explanations: Optional[str] = None

class StandardisedProperties(BaseModel):
    entity_id: Optional[str] = None
    properties: Dict[str, Optional[str]]
