###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class ResolutionStrategy(str, Enum):
    KEEP_STAGING = "staging"
    KEEP_PRODUCTION = "production"
    CUSTOM = "custom"
    KEEP_BOTH = "both"

class ChangeResult(BaseModel):
    id: str
    corrections: List["Correction"]
    confidence_score: float

class ConflictAnalysis(BaseModel):
    description: str
    potential_causes: List[str]
    semantic_meaning: str
    impact: str
    key_differences: List[str]

class ConflictClassification(BaseModel):
    category: str
    explanation: str
    confidence: float

class ConflictGroupAnalysis(BaseModel):
    pattern: str
    batch_resolvable: bool
    recommended_strategy: "ResolutionStrategy"
    confidence: float
    risks: List[str]

class Correction(BaseModel):
    prop_name: str
    prop_value: str

class DynamicContainer(BaseModel):
    model_config = ConfigDict(extra='allow')

class EntitySimilarityAnalysis(BaseModel):
    similarity_score: float
    confidence: float
    matching_properties: List[str]
    mismatched_properties: List[str]
    semantic_similarity: float
    potential_merge_impact: str
    recommended_action: str
    reasoning: str

class MatchingNode(BaseModel):
    staging_node_id: str
    node_id: str
    confidence: float

class PropertyConflictAnalysis(BaseModel):
    recommended_strategy: "ResolutionStrategy"
    confidence: float
    explanation: str
    can_auto_resolve: bool
    potential_risks: List[str]

class RelationshipConflictAnalysis(BaseModel):
    recommended_strategy: "ResolutionStrategy"
    confidence: float
    explanation: str
    can_auto_resolve: bool
    semantic_impact: str
    risks: List[str]

class RelationshipInference(BaseModel):
    id: str
    type: str
    source_id: str
    target_id: str
    source_type: str
    target_type: str
    properties: Dict[str, str]
    confidence_score: float

class ResolutionOption(BaseModel):
    id: str
    description: str
    resolution_type: str
    resolution_data: "JsonObject"
    confidence: float
    reasoning: str

class ResolutionOptions(BaseModel):
    options: List["ResolutionOption"]
    recommended_option_id: str
    recommendation_reasoning: str

class ResolvedEntities(BaseModel):
    matching_ids: List[str]
    confidence_score: float
    explanation: str

class SelectedResolution(BaseModel):
    option_id: str
    resolution_type: str
    resolution_data: "JsonObject"
    confidence: float

class StandardisedProperties(BaseModel):
    entity_id: str
    properties: Dict[str, str]

JsonArray: TypeAlias = List["JsonValue"]

JsonObject: TypeAlias = Dict[str, "JsonValue"]

JsonValue: TypeAlias = Union[int, str, bool, float, "JsonObject", "JsonArray"]
