###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, Union, TypedDict, Type
from typing_extensions import NotRequired, Literal

import baml_py

from . import types
from .types import Checked, Check
from .type_builder import TypeBuilder


class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]


class AsyncHttpRequest:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    async def AnalyzeConflict(
        self,
        entity_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeConflict",
        {
          "entity_type": entity_type,
          "property_name": property_name,
          "staging_value": staging_value,
          "production_value": production_value,
          "value_type": value_type,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeConflictGroup(
        self,
        entity_type: str,property_name: str,value_type: str,conflict_count: int,sample_conflicts: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeConflictGroup",
        {
          "entity_type": entity_type,
          "property_name": property_name,
          "value_type": value_type,
          "conflict_count": conflict_count,
          "sample_conflicts": sample_conflicts,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeDuplicateEntityConflict(
        self,
        entity_type: str,staging_entity_id: str,production_entity_ids: str,similarity_scores: str,entity_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeDuplicateEntityConflict",
        {
          "entity_type": entity_type,
          "staging_entity_id": staging_entity_id,
          "production_entity_ids": production_entity_ids,
          "similarity_scores": similarity_scores,
          "entity_properties": entity_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeEntityMatchConflict(
        self,
        entity_type: str,staging_entity_id: str,production_entity_id: str,match_confidence: float,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntityMatchConflict",
        {
          "entity_type": entity_type,
          "staging_entity_id": staging_entity_id,
          "production_entity_id": production_entity_id,
          "match_confidence": match_confidence,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeEntityMatchConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntityMatchConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeEntityMatchResolutionOption(
        self,
        entity_type: str,resolution_option: str,staging_entity_id: str,production_entity_id: str,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntityMatchResolutionOption",
        {
          "entity_type": entity_type,
          "resolution_option": resolution_option,
          "staging_entity_id": staging_entity_id,
          "production_entity_id": production_entity_id,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeEntityMatchWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntityMatchWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeEntitySimilarity(
        self,
        entity_type: str,staging_properties: str,production_properties: str,domain_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntitySimilarity",
        {
          "entity_type": entity_type,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
          "domain_context": domain_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeGenericConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeGenericConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeMissingRelationshipConflict(
        self,
        relationship_type: str,source_entity_type: str,target_entity_type: str,source_entity_id: str,target_entity_id: str,exists_in: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeMissingRelationshipConflict",
        {
          "relationship_type": relationship_type,
          "source_entity_type": source_entity_type,
          "target_entity_type": target_entity_type,
          "source_entity_id": source_entity_id,
          "target_entity_id": target_entity_id,
          "exists_in": exists_in,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzePropertyConflict(
        self,
        entity_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,historical_resolutions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzePropertyConflict",
        {
          "entity_type": entity_type,
          "property_name": property_name,
          "staging_value": staging_value,
          "production_value": production_value,
          "value_type": value_type,
          "historical_resolutions": historical_resolutions,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzePropertyConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzePropertyConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeRelationshipConflict(
        self,
        relationship_type: str,conflict_type: str,staging_details: str,production_details: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipConflict",
        {
          "relationship_type": relationship_type,
          "conflict_type": conflict_type,
          "staging_details": staging_details,
          "production_details": production_details,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeRelationshipConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeRelationshipDirectionConflict(
        self,
        relationship_type: str,staging_source_id: str,staging_target_id: str,production_source_id: str,production_target_id: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipDirectionConflict",
        {
          "relationship_type": relationship_type,
          "staging_source_id": staging_source_id,
          "staging_target_id": staging_target_id,
          "production_source_id": production_source_id,
          "production_target_id": production_target_id,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeRelationshipPropertyConflict(
        self,
        relationship_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipPropertyConflict",
        {
          "relationship_type": relationship_type,
          "property_name": property_name,
          "staging_value": staging_value,
          "production_value": production_value,
          "value_type": value_type,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeRelationshipTypeConflict(
        self,
        staging_relationship_type: str,production_relationship_type: str,source_entity_type: str,target_entity_type: str,source_entity_id: str,target_entity_id: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipTypeConflict",
        {
          "staging_relationship_type": staging_relationship_type,
          "production_relationship_type": production_relationship_type,
          "source_entity_type": source_entity_type,
          "target_entity_type": target_entity_type,
          "source_entity_id": source_entity_id,
          "target_entity_id": target_entity_id,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeSchemaConflict(
        self,
        entity_type: str,conflict_description: str,staging_schema: str,production_schema: str,affected_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeSchemaConflict",
        {
          "entity_type": entity_type,
          "conflict_description": conflict_description,
          "staging_schema": staging_schema,
          "production_schema": production_schema,
          "affected_properties": affected_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AnalyzeSchemaConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeSchemaConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def AssessResolutionComplexity(
        self,
        conflict_type: str,classification: str,resolution_option: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AssessResolutionComplexity",
        {
          "conflict_type": conflict_type,
          "classification": classification,
          "resolution_option": resolution_option,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def BatchAnalyzeConflicts(
        self,
        conflict_type: str,entity_type: str,conflict_summaries: str,sample_conflicts: str,total_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "BatchAnalyzeConflicts",
        {
          "conflict_type": conflict_type,
          "entity_type": entity_type,
          "conflict_summaries": conflict_summaries,
          "sample_conflicts": sample_conflicts,
          "total_count": total_count,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def ClassifyConflict(
        self,
        analysis: str,conflict_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ClassifyConflict",
        {
          "analysis": analysis,
          "conflict_type": conflict_type,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def ComprehensiveRefinement(
        self,
        chunk: str,gaps_context: str,existing_entities: str,existing_relationships: str,ontology_yaml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ComprehensiveRefinement",
        {
          "chunk": chunk,
          "gaps_context": gaps_context,
          "existing_entities": existing_entities,
          "existing_relationships": existing_relationships,
          "ontology_yaml": ontology_yaml,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def EvalChanges(
        self,
        change_logs: str,past_resolutions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "EvalChanges",
        {
          "change_logs": change_logs,
          "past_resolutions": past_resolutions,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def ExtractExpectedRelationships(
        self,
        chunk: str,source_entity: str,expected_relationship_type: str,target_entity_type: str,potential_targets: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ExtractExpectedRelationships",
        {
          "chunk": chunk,
          "source_entity": source_entity,
          "expected_relationship_type": expected_relationship_type,
          "target_entity_type": target_entity_type,
          "potential_targets": potential_targets,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def ExtractNodesFromChunk(
        self,
        chunk: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ExtractNodesFromChunk",
        {
          "chunk": chunk,
          "context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def ExtractRelationshipsFromChunk(
        self,
        chunk: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ExtractRelationshipsFromChunk",
        {
          "chunk": chunk,
          "context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def FindMissingRelationships(
        self,
        chunk: str,orphan_nodes: str,existing_relationships: str,ontology_relationships: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "FindMissingRelationships",
        {
          "chunk": chunk,
          "orphan_nodes": orphan_nodes,
          "existing_relationships": existing_relationships,
          "ontology_relationships": ontology_relationships,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def GenerateEntityMatchResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateEntityMatchResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def GenerateEntityMatchResolutionOptionsFromStagingAndProd(
        self,
        conflict_analysis: str,entity_type: str,staging_entity_id: str,production_entity_id: str,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateEntityMatchResolutionOptionsFromStagingAndProd",
        {
          "conflict_analysis": conflict_analysis,
          "entity_type": entity_type,
          "staging_entity_id": staging_entity_id,
          "production_entity_id": production_entity_id,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def GenerateGenericResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateGenericResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def GenerateKnowledgeGraphSchema(
        self,
        use_case: str,domain: str,data_sources: str,key_entities: str,relationships: str,query_patterns: str,data_complexity: str,data_volume: str,temporal_requirements: str,related_schemas: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateKnowledgeGraphSchema",
        {
          "use_case": use_case,
          "domain": domain,
          "data_sources": data_sources,
          "key_entities": key_entities,
          "relationships": relationships,
          "query_patterns": query_patterns,
          "data_complexity": data_complexity,
          "data_volume": data_volume,
          "temporal_requirements": temporal_requirements,
          "related_schemas": related_schemas,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def GeneratePropertyResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GeneratePropertyResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def GenerateRelationshipResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateRelationshipResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def GenerateResolutionOptions(
        self,
        conflict_analysis: str,classification: str,staging_element: str,prod_element: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateResolutionOptions",
        {
          "conflict_analysis": conflict_analysis,
          "classification": classification,
          "staging_element": staging_element,
          "prod_element": prod_element,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def GenerateSchemaConflictResolutionOptions(
        self,
        conflict_analysis: str,entity_type: str,staging_schema: str,production_schema: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateSchemaConflictResolutionOptions",
        {
          "conflict_analysis": conflict_analysis,
          "entity_type": entity_type,
          "staging_schema": staging_schema,
          "production_schema": production_schema,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def GetMatchingNodes(
        self,
        candidate_sets: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GetMatchingNodes",
        {
          "candidate_sets": candidate_sets,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def InferRelationship(
        self,
        rel_type: str,source_type: str,target_type: str,source_entities: str,target_entities: str,existing_rels: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "InferRelationship",
        {
          "rel_type": rel_type,
          "source_type": source_type,
          "target_type": target_type,
          "source_entities": source_entities,
          "target_entities": target_entities,
          "existing_rels": existing_rels,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RefineIncompleteEntity(
        self,
        chunk: str,entity_context: str,missing_properties: str,entity_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RefineIncompleteEntity",
        {
          "chunk": chunk,
          "entity_context": entity_context,
          "missing_properties": missing_properties,
          "entity_type": entity_type,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RefineKnowledgeGraphSchema(
        self,
        current_schema_yaml: str,user_feedback: str,use_case: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RefineKnowledgeGraphSchema",
        {
          "current_schema_yaml": current_schema_yaml,
          "user_feedback": user_feedback,
          "use_case": use_case,
          "domain": domain,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RefineSchemaConversational(
        self,
        current_schema: str,user_request: str,refinement_count: int,previous_requests_summary: str,changes_history_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RefineSchemaConversational",
        {
          "current_schema": current_schema,
          "user_request": user_request,
          "refinement_count": refinement_count,
          "previous_requests_summary": previous_requests_summary,
          "changes_history_summary": changes_history_summary,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def RefineUncertainEntities(
        self,
        chunk: str,uncertain_entities: str,ontology_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RefineUncertainEntities",
        {
          "chunk": chunk,
          "uncertain_entities": uncertain_entities,
          "ontology_context": ontology_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def ResolveEntities(
        self,
        entity_type: str,node_dicts_str: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ResolveEntities",
        {
          "entity_type": entity_type,
          "node_dicts_str": node_dicts_str,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def SelectBestResolution(
        self,
        conflict: types.JsonObject,options: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SelectBestResolution",
        {
          "conflict": conflict,
          "options": options,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    
    async def StandardiseProperties(
        self,
        entity_group_type: str,entities_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "StandardiseProperties",
        {
          "entity_group_type": entity_group_type,
          "entities_json": entities_json,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        False,
      )
    


class AsyncHttpStreamRequest:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    async def AnalyzeConflict(
        self,
        entity_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeConflict",
        {
          "entity_type": entity_type,
          "property_name": property_name,
          "staging_value": staging_value,
          "production_value": production_value,
          "value_type": value_type,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeConflictGroup(
        self,
        entity_type: str,property_name: str,value_type: str,conflict_count: int,sample_conflicts: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeConflictGroup",
        {
          "entity_type": entity_type,
          "property_name": property_name,
          "value_type": value_type,
          "conflict_count": conflict_count,
          "sample_conflicts": sample_conflicts,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeDuplicateEntityConflict(
        self,
        entity_type: str,staging_entity_id: str,production_entity_ids: str,similarity_scores: str,entity_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeDuplicateEntityConflict",
        {
          "entity_type": entity_type,
          "staging_entity_id": staging_entity_id,
          "production_entity_ids": production_entity_ids,
          "similarity_scores": similarity_scores,
          "entity_properties": entity_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeEntityMatchConflict(
        self,
        entity_type: str,staging_entity_id: str,production_entity_id: str,match_confidence: float,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntityMatchConflict",
        {
          "entity_type": entity_type,
          "staging_entity_id": staging_entity_id,
          "production_entity_id": production_entity_id,
          "match_confidence": match_confidence,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeEntityMatchConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntityMatchConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeEntityMatchResolutionOption(
        self,
        entity_type: str,resolution_option: str,staging_entity_id: str,production_entity_id: str,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntityMatchResolutionOption",
        {
          "entity_type": entity_type,
          "resolution_option": resolution_option,
          "staging_entity_id": staging_entity_id,
          "production_entity_id": production_entity_id,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeEntityMatchWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntityMatchWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeEntitySimilarity(
        self,
        entity_type: str,staging_properties: str,production_properties: str,domain_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeEntitySimilarity",
        {
          "entity_type": entity_type,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
          "domain_context": domain_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeGenericConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeGenericConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeMissingRelationshipConflict(
        self,
        relationship_type: str,source_entity_type: str,target_entity_type: str,source_entity_id: str,target_entity_id: str,exists_in: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeMissingRelationshipConflict",
        {
          "relationship_type": relationship_type,
          "source_entity_type": source_entity_type,
          "target_entity_type": target_entity_type,
          "source_entity_id": source_entity_id,
          "target_entity_id": target_entity_id,
          "exists_in": exists_in,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzePropertyConflict(
        self,
        entity_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,historical_resolutions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzePropertyConflict",
        {
          "entity_type": entity_type,
          "property_name": property_name,
          "staging_value": staging_value,
          "production_value": production_value,
          "value_type": value_type,
          "historical_resolutions": historical_resolutions,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzePropertyConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzePropertyConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeRelationshipConflict(
        self,
        relationship_type: str,conflict_type: str,staging_details: str,production_details: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipConflict",
        {
          "relationship_type": relationship_type,
          "conflict_type": conflict_type,
          "staging_details": staging_details,
          "production_details": production_details,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeRelationshipConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeRelationshipDirectionConflict(
        self,
        relationship_type: str,staging_source_id: str,staging_target_id: str,production_source_id: str,production_target_id: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipDirectionConflict",
        {
          "relationship_type": relationship_type,
          "staging_source_id": staging_source_id,
          "staging_target_id": staging_target_id,
          "production_source_id": production_source_id,
          "production_target_id": production_target_id,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeRelationshipPropertyConflict(
        self,
        relationship_type: str,property_name: str,staging_value: str,production_value: str,value_type: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipPropertyConflict",
        {
          "relationship_type": relationship_type,
          "property_name": property_name,
          "staging_value": staging_value,
          "production_value": production_value,
          "value_type": value_type,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeRelationshipTypeConflict(
        self,
        staging_relationship_type: str,production_relationship_type: str,source_entity_type: str,target_entity_type: str,source_entity_id: str,target_entity_id: str,graph_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeRelationshipTypeConflict",
        {
          "staging_relationship_type": staging_relationship_type,
          "production_relationship_type": production_relationship_type,
          "source_entity_type": source_entity_type,
          "target_entity_type": target_entity_type,
          "source_entity_id": source_entity_id,
          "target_entity_id": target_entity_id,
          "graph_context": graph_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeSchemaConflict(
        self,
        entity_type: str,conflict_description: str,staging_schema: str,production_schema: str,affected_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeSchemaConflict",
        {
          "entity_type": entity_type,
          "conflict_description": conflict_description,
          "staging_schema": staging_schema,
          "production_schema": production_schema,
          "affected_properties": affected_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AnalyzeSchemaConflictWithOntology(
        self,
        conflict: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AnalyzeSchemaConflictWithOntology",
        {
          "conflict": conflict,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def AssessResolutionComplexity(
        self,
        conflict_type: str,classification: str,resolution_option: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "AssessResolutionComplexity",
        {
          "conflict_type": conflict_type,
          "classification": classification,
          "resolution_option": resolution_option,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def BatchAnalyzeConflicts(
        self,
        conflict_type: str,entity_type: str,conflict_summaries: str,sample_conflicts: str,total_count: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "BatchAnalyzeConflicts",
        {
          "conflict_type": conflict_type,
          "entity_type": entity_type,
          "conflict_summaries": conflict_summaries,
          "sample_conflicts": sample_conflicts,
          "total_count": total_count,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def ClassifyConflict(
        self,
        analysis: str,conflict_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ClassifyConflict",
        {
          "analysis": analysis,
          "conflict_type": conflict_type,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def ComprehensiveRefinement(
        self,
        chunk: str,gaps_context: str,existing_entities: str,existing_relationships: str,ontology_yaml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ComprehensiveRefinement",
        {
          "chunk": chunk,
          "gaps_context": gaps_context,
          "existing_entities": existing_entities,
          "existing_relationships": existing_relationships,
          "ontology_yaml": ontology_yaml,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def EvalChanges(
        self,
        change_logs: str,past_resolutions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "EvalChanges",
        {
          "change_logs": change_logs,
          "past_resolutions": past_resolutions,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def ExtractExpectedRelationships(
        self,
        chunk: str,source_entity: str,expected_relationship_type: str,target_entity_type: str,potential_targets: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ExtractExpectedRelationships",
        {
          "chunk": chunk,
          "source_entity": source_entity,
          "expected_relationship_type": expected_relationship_type,
          "target_entity_type": target_entity_type,
          "potential_targets": potential_targets,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def ExtractNodesFromChunk(
        self,
        chunk: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ExtractNodesFromChunk",
        {
          "chunk": chunk,
          "context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def ExtractRelationshipsFromChunk(
        self,
        chunk: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ExtractRelationshipsFromChunk",
        {
          "chunk": chunk,
          "context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def FindMissingRelationships(
        self,
        chunk: str,orphan_nodes: str,existing_relationships: str,ontology_relationships: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "FindMissingRelationships",
        {
          "chunk": chunk,
          "orphan_nodes": orphan_nodes,
          "existing_relationships": existing_relationships,
          "ontology_relationships": ontology_relationships,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def GenerateEntityMatchResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateEntityMatchResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def GenerateEntityMatchResolutionOptionsFromStagingAndProd(
        self,
        conflict_analysis: str,entity_type: str,staging_entity_id: str,production_entity_id: str,staging_properties: str,production_properties: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateEntityMatchResolutionOptionsFromStagingAndProd",
        {
          "conflict_analysis": conflict_analysis,
          "entity_type": entity_type,
          "staging_entity_id": staging_entity_id,
          "production_entity_id": production_entity_id,
          "staging_properties": staging_properties,
          "production_properties": production_properties,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def GenerateGenericResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateGenericResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def GenerateKnowledgeGraphSchema(
        self,
        use_case: str,domain: str,data_sources: str,key_entities: str,relationships: str,query_patterns: str,data_complexity: str,data_volume: str,temporal_requirements: str,related_schemas: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateKnowledgeGraphSchema",
        {
          "use_case": use_case,
          "domain": domain,
          "data_sources": data_sources,
          "key_entities": key_entities,
          "relationships": relationships,
          "query_patterns": query_patterns,
          "data_complexity": data_complexity,
          "data_volume": data_volume,
          "temporal_requirements": temporal_requirements,
          "related_schemas": related_schemas,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def GeneratePropertyResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GeneratePropertyResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def GenerateRelationshipResolutionOptions(
        self,
        conflict: types.JsonObject,analysis: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateRelationshipResolutionOptions",
        {
          "conflict": conflict,
          "analysis": analysis,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def GenerateResolutionOptions(
        self,
        conflict_analysis: str,classification: str,staging_element: str,prod_element: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateResolutionOptions",
        {
          "conflict_analysis": conflict_analysis,
          "classification": classification,
          "staging_element": staging_element,
          "prod_element": prod_element,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def GenerateSchemaConflictResolutionOptions(
        self,
        conflict_analysis: str,entity_type: str,staging_schema: str,production_schema: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GenerateSchemaConflictResolutionOptions",
        {
          "conflict_analysis": conflict_analysis,
          "entity_type": entity_type,
          "staging_schema": staging_schema,
          "production_schema": production_schema,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def GetMatchingNodes(
        self,
        candidate_sets: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "GetMatchingNodes",
        {
          "candidate_sets": candidate_sets,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def InferRelationship(
        self,
        rel_type: str,source_type: str,target_type: str,source_entities: str,target_entities: str,existing_rels: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "InferRelationship",
        {
          "rel_type": rel_type,
          "source_type": source_type,
          "target_type": target_type,
          "source_entities": source_entities,
          "target_entities": target_entities,
          "existing_rels": existing_rels,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RefineIncompleteEntity(
        self,
        chunk: str,entity_context: str,missing_properties: str,entity_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RefineIncompleteEntity",
        {
          "chunk": chunk,
          "entity_context": entity_context,
          "missing_properties": missing_properties,
          "entity_type": entity_type,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RefineKnowledgeGraphSchema(
        self,
        current_schema_yaml: str,user_feedback: str,use_case: str,domain: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RefineKnowledgeGraphSchema",
        {
          "current_schema_yaml": current_schema_yaml,
          "user_feedback": user_feedback,
          "use_case": use_case,
          "domain": domain,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RefineSchemaConversational(
        self,
        current_schema: str,user_request: str,refinement_count: int,previous_requests_summary: str,changes_history_summary: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RefineSchemaConversational",
        {
          "current_schema": current_schema,
          "user_request": user_request,
          "refinement_count": refinement_count,
          "previous_requests_summary": previous_requests_summary,
          "changes_history_summary": changes_history_summary,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def RefineUncertainEntities(
        self,
        chunk: str,uncertain_entities: str,ontology_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "RefineUncertainEntities",
        {
          "chunk": chunk,
          "uncertain_entities": uncertain_entities,
          "ontology_context": ontology_context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def ResolveEntities(
        self,
        entity_type: str,node_dicts_str: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "ResolveEntities",
        {
          "entity_type": entity_type,
          "node_dicts_str": node_dicts_str,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def SelectBestResolution(
        self,
        conflict: types.JsonObject,options: types.JsonObject,ontology: types.JsonObject,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "SelectBestResolution",
        {
          "conflict": conflict,
          "options": options,
          "ontology": ontology,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    
    async def StandardiseProperties(
        self,
        entity_group_type: str,entities_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.HTTPRequest:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      return await self.__runtime.build_request(
        "StandardiseProperties",
        {
          "entity_group_type": entity_group_type,
          "entities_json": entities_json,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        True,
      )
    


__all__ = ["AsyncHttpRequest", "AsyncHttpStreamRequest"]