###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class ChangeResult(BaseModel):
    id: Optional[str] = None
    corrections: List["Correction"]
    confidence_score: Optional[float] = None

class ConflictAnalysis(BaseModel):
    description: Optional[str] = None
    potential_causes: List[str]
    semantic_meaning: Optional[str] = None
    impact: Optional[str] = None
    key_differences: List[str]

class ConflictClassification(BaseModel):
    category: Optional[str] = None
    explanation: Optional[str] = None
    confidence: Optional[float] = None

class ConflictGroupAnalysis(BaseModel):
    pattern: Optional[str] = None
    batch_resolvable: Optional[bool] = None
    recommended_strategy: Optional[types.ResolutionStrategy] = None
    confidence: Optional[float] = None
    risks: List[str]

class Correction(BaseModel):
    prop_name: Optional[str] = None
    prop_value: Optional[str] = None

class DynamicContainer(BaseModel):
    model_config = ConfigDict(extra='allow')

class Entity(BaseModel):
    properties: Dict[str, Optional["EntityProperty"]]
    relationships: Optional[Dict[str, Optional["Relationship"]]] = None

class EntityProperty(BaseModel):
    type: Optional[str] = None
    description: Optional[str] = None
    required: Optional[bool] = None
    unique: Optional[bool] = None
    index: Optional[bool] = None

class EntitySimilarityAnalysis(BaseModel):
    similarity_score: Optional[float] = None
    confidence: Optional[float] = None
    matching_properties: List[str]
    mismatched_properties: List[str]
    semantic_similarity: Optional[float] = None
    potential_merge_impact: Optional[str] = None
    recommended_action: Optional[str] = None
    reasoning: Optional[str] = None

class GeneratedSchema(BaseModel):
    version: Optional[str] = None
    entities: Dict[str, Optional["Entity"]]

class MatchingNode(BaseModel):
    staging_node_id: Optional[str] = None
    node_id: Optional[str] = None
    confidence: Optional[float] = None

class PropertyConflictAnalysis(BaseModel):
    recommended_strategy: Optional[types.ResolutionStrategy] = None
    confidence: Optional[float] = None
    explanation: Optional[str] = None
    can_auto_resolve: Optional[bool] = None
    potential_risks: List[str]

class Relationship(BaseModel):
    target: Optional[str] = None
    properties: Optional[Dict[str, Optional["RelationshipProperty"]]] = None

class RelationshipConflictAnalysis(BaseModel):
    recommended_strategy: Optional[types.ResolutionStrategy] = None
    confidence: Optional[float] = None
    explanation: Optional[str] = None
    can_auto_resolve: Optional[bool] = None
    semantic_impact: Optional[str] = None
    risks: List[str]

class RelationshipInference(BaseModel):
    id: Optional[str] = None
    type: Optional[str] = None
    source_id: Optional[str] = None
    target_id: Optional[str] = None
    source_type: Optional[str] = None
    target_type: Optional[str] = None
    properties: Dict[str, Optional[str]]
    confidence_score: Optional[float] = None

class RelationshipProperty(BaseModel):
    type: Optional[str] = None
    description: Optional[str] = None
    required: Optional[bool] = None

class ResolutionOption(BaseModel):
    id: Optional[str] = None
    description: Optional[str] = None
    resolution_type: Optional[str] = None
    resolution_data: Optional["JsonObject"] = None
    confidence: Optional[float] = None
    reasoning: Optional[str] = None

class ResolutionOptions(BaseModel):
    options: List["ResolutionOption"]
    recommended_option_id: Optional[str] = None
    recommendation_reasoning: Optional[str] = None

class ResolvedEntities(BaseModel):
    matching_ids: List[str]
    confidence_score: Optional[float] = None
    explanation: Optional[str] = None

class SchemaGenerationResult(BaseModel):
    generated_schema: Optional["GeneratedSchema"] = None
    confidence: Optional[float] = None
    suggestions: List[str]
    explanation: Optional[str] = None

class SchemaRefinementResponse(BaseModel):
    refined_schema: Optional[str] = None
    changes_made: List[str]
    confidence: Optional[float] = None
    explanation: Optional[str] = None

class SelectedResolution(BaseModel):
    option_id: Optional[str] = None
    resolution_type: Optional[str] = None
    resolution_data: Optional["JsonObject"] = None
    confidence: Optional[float] = None

class StandardisedProperties(BaseModel):
    entity_id: Optional[str] = None
    properties: Dict[str, Optional[str]]

JsonArray: TypeAlias = List["JsonValue"]

JsonObject: TypeAlias = Dict[str, "JsonValue"]

JsonValue: TypeAlias = Union[int, str, bool, float, "JsonObject", "JsonArray"]
