###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import typing
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder
from baml_py.type_builder import TypeBuilder as _TypeBuilder, ClassPropertyBuilder, ClassPropertyViewer, EnumValueViewer
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(_TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["ChangeResult","ConflictAnalysis","ConflictClassification","ConflictGroupAnalysis","Correction","DynamicContainer","Entity","EntityProperty","EntitySimilarityAnalysis","GeneratedSchema","MatchingNode","PropertyConflictAnalysis","Relationship","RelationshipConflictAnalysis","RelationshipInference","RelationshipProperty","ResolutionOption","ResolutionOptions","ResolvedEntities","SchemaGenerationResult","SchemaRefinementResponse","SelectedResolution","StandardisedProperties",]
        ), enums=set(
          ["ResolutionStrategy",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)


    @property
    def ChangeResult(self) -> "ChangeResultAst":
        return ChangeResultAst(self)

    @property
    def ConflictAnalysis(self) -> "ConflictAnalysisAst":
        return ConflictAnalysisAst(self)

    @property
    def ConflictClassification(self) -> "ConflictClassificationAst":
        return ConflictClassificationAst(self)

    @property
    def ConflictGroupAnalysis(self) -> "ConflictGroupAnalysisAst":
        return ConflictGroupAnalysisAst(self)

    @property
    def Correction(self) -> "CorrectionAst":
        return CorrectionAst(self)

    
    @property
    def DynamicContainer(self) -> "DynamicContainerBuilder":
        return DynamicContainerBuilder(self)

    @property
    def Entity(self) -> "EntityAst":
        return EntityAst(self)

    @property
    def EntityProperty(self) -> "EntityPropertyAst":
        return EntityPropertyAst(self)

    @property
    def EntitySimilarityAnalysis(self) -> "EntitySimilarityAnalysisAst":
        return EntitySimilarityAnalysisAst(self)

    @property
    def GeneratedSchema(self) -> "GeneratedSchemaAst":
        return GeneratedSchemaAst(self)

    @property
    def MatchingNode(self) -> "MatchingNodeAst":
        return MatchingNodeAst(self)

    @property
    def PropertyConflictAnalysis(self) -> "PropertyConflictAnalysisAst":
        return PropertyConflictAnalysisAst(self)

    @property
    def Relationship(self) -> "RelationshipAst":
        return RelationshipAst(self)

    @property
    def RelationshipConflictAnalysis(self) -> "RelationshipConflictAnalysisAst":
        return RelationshipConflictAnalysisAst(self)

    @property
    def RelationshipInference(self) -> "RelationshipInferenceAst":
        return RelationshipInferenceAst(self)

    @property
    def RelationshipProperty(self) -> "RelationshipPropertyAst":
        return RelationshipPropertyAst(self)

    @property
    def ResolutionOption(self) -> "ResolutionOptionAst":
        return ResolutionOptionAst(self)

    @property
    def ResolutionOptions(self) -> "ResolutionOptionsAst":
        return ResolutionOptionsAst(self)

    @property
    def ResolvedEntities(self) -> "ResolvedEntitiesAst":
        return ResolvedEntitiesAst(self)

    @property
    def SchemaGenerationResult(self) -> "SchemaGenerationResultAst":
        return SchemaGenerationResultAst(self)

    @property
    def SchemaRefinementResponse(self) -> "SchemaRefinementResponseAst":
        return SchemaRefinementResponseAst(self)

    @property
    def SelectedResolution(self) -> "SelectedResolutionAst":
        return SelectedResolutionAst(self)

    @property
    def StandardisedProperties(self) -> "StandardisedPropertiesAst":
        return StandardisedPropertiesAst(self)





class ChangeResultAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ChangeResult")
        self._properties: typing.Set[str] = set([ "id",  "corrections",  "confidence_score", ])
        self._props = ChangeResultProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ChangeResultProperties":
        return self._props


class ChangeResultViewer(ChangeResultAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ChangeResultProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("id"))

    @property
    def corrections(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("corrections"))

    @property
    def confidence_score(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence_score"))

    

class ConflictAnalysisAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ConflictAnalysis")
        self._properties: typing.Set[str] = set([ "description",  "potential_causes",  "semantic_meaning",  "impact",  "key_differences", ])
        self._props = ConflictAnalysisProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ConflictAnalysisProperties":
        return self._props


class ConflictAnalysisViewer(ConflictAnalysisAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ConflictAnalysisProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def description(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def potential_causes(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("potential_causes"))

    @property
    def semantic_meaning(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("semantic_meaning"))

    @property
    def impact(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("impact"))

    @property
    def key_differences(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("key_differences"))

    

class ConflictClassificationAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ConflictClassification")
        self._properties: typing.Set[str] = set([ "category",  "explanation",  "confidence", ])
        self._props = ConflictClassificationProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ConflictClassificationProperties":
        return self._props


class ConflictClassificationViewer(ConflictClassificationAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ConflictClassificationProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def category(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("category"))

    @property
    def explanation(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("explanation"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    

class ConflictGroupAnalysisAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ConflictGroupAnalysis")
        self._properties: typing.Set[str] = set([ "pattern",  "batch_resolvable",  "recommended_strategy",  "confidence",  "risks", ])
        self._props = ConflictGroupAnalysisProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ConflictGroupAnalysisProperties":
        return self._props


class ConflictGroupAnalysisViewer(ConflictGroupAnalysisAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ConflictGroupAnalysisProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def pattern(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("pattern"))

    @property
    def batch_resolvable(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("batch_resolvable"))

    @property
    def recommended_strategy(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("recommended_strategy"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    @property
    def risks(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("risks"))

    

class CorrectionAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Correction")
        self._properties: typing.Set[str] = set([ "prop_name",  "prop_value", ])
        self._props = CorrectionProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CorrectionProperties":
        return self._props


class CorrectionViewer(CorrectionAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class CorrectionProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def prop_name(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("prop_name"))

    @property
    def prop_value(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("prop_value"))

    

class DynamicContainerAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("DynamicContainer")
        self._properties: typing.Set[str] = set([])
        self._props = DynamicContainerProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "DynamicContainerProperties":
        return self._props


class DynamicContainerBuilder(DynamicContainerAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    def add_property(self, name: str, type: FieldType) -> ClassPropertyBuilder:
        if name in self._properties:
            raise ValueError(f"Property {name} already exists.")
        return ClassPropertyBuilder(self._bldr.property(name).type(type))

    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyBuilder]]:
        return [(name, ClassPropertyBuilder(self._bldr.property(name))) for name in self._properties]



class DynamicContainerProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    
    def __getattr__(self, name: str) -> ClassPropertyBuilder:
        if name not in self.__properties:
            raise AttributeError(f"Property {name} not found.")
        return ClassPropertyBuilder(self.__bldr.property(name))
    

class EntityAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Entity")
        self._properties: typing.Set[str] = set([ "properties",  "relationships", ])
        self._props = EntityProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EntityProperties":
        return self._props


class EntityViewer(EntityAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class EntityProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def properties(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("properties"))

    @property
    def relationships(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("relationships"))

    

class EntityPropertyAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("EntityProperty")
        self._properties: typing.Set[str] = set([ "type",  "description",  "required",  "unique",  "index", ])
        self._props = EntityPropertyProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EntityPropertyProperties":
        return self._props


class EntityPropertyViewer(EntityPropertyAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class EntityPropertyProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def type(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("type"))

    @property
    def description(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def required(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("required"))

    @property
    def unique(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("unique"))

    @property
    def index(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("index"))

    

class EntitySimilarityAnalysisAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("EntitySimilarityAnalysis")
        self._properties: typing.Set[str] = set([ "similarity_score",  "confidence",  "matching_properties",  "mismatched_properties",  "semantic_similarity",  "potential_merge_impact",  "recommended_action",  "reasoning", ])
        self._props = EntitySimilarityAnalysisProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EntitySimilarityAnalysisProperties":
        return self._props


class EntitySimilarityAnalysisViewer(EntitySimilarityAnalysisAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class EntitySimilarityAnalysisProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def similarity_score(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("similarity_score"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    @property
    def matching_properties(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("matching_properties"))

    @property
    def mismatched_properties(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("mismatched_properties"))

    @property
    def semantic_similarity(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("semantic_similarity"))

    @property
    def potential_merge_impact(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("potential_merge_impact"))

    @property
    def recommended_action(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("recommended_action"))

    @property
    def reasoning(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("reasoning"))

    

class GeneratedSchemaAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("GeneratedSchema")
        self._properties: typing.Set[str] = set([ "version",  "entities", ])
        self._props = GeneratedSchemaProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "GeneratedSchemaProperties":
        return self._props


class GeneratedSchemaViewer(GeneratedSchemaAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class GeneratedSchemaProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def version(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("version"))

    @property
    def entities(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("entities"))

    

class MatchingNodeAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("MatchingNode")
        self._properties: typing.Set[str] = set([ "staging_node_id",  "node_id",  "confidence", ])
        self._props = MatchingNodeProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "MatchingNodeProperties":
        return self._props


class MatchingNodeViewer(MatchingNodeAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class MatchingNodeProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def staging_node_id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("staging_node_id"))

    @property
    def node_id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("node_id"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    

class PropertyConflictAnalysisAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("PropertyConflictAnalysis")
        self._properties: typing.Set[str] = set([ "recommended_strategy",  "confidence",  "explanation",  "can_auto_resolve",  "potential_risks", ])
        self._props = PropertyConflictAnalysisProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PropertyConflictAnalysisProperties":
        return self._props


class PropertyConflictAnalysisViewer(PropertyConflictAnalysisAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class PropertyConflictAnalysisProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def recommended_strategy(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("recommended_strategy"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    @property
    def explanation(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("explanation"))

    @property
    def can_auto_resolve(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("can_auto_resolve"))

    @property
    def potential_risks(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("potential_risks"))

    

class RelationshipAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Relationship")
        self._properties: typing.Set[str] = set([ "target",  "properties", ])
        self._props = RelationshipProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RelationshipProperties":
        return self._props


class RelationshipViewer(RelationshipAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class RelationshipProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def target(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("target"))

    @property
    def properties(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("properties"))

    

class RelationshipConflictAnalysisAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RelationshipConflictAnalysis")
        self._properties: typing.Set[str] = set([ "recommended_strategy",  "confidence",  "explanation",  "can_auto_resolve",  "semantic_impact",  "risks", ])
        self._props = RelationshipConflictAnalysisProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RelationshipConflictAnalysisProperties":
        return self._props


class RelationshipConflictAnalysisViewer(RelationshipConflictAnalysisAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class RelationshipConflictAnalysisProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def recommended_strategy(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("recommended_strategy"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    @property
    def explanation(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("explanation"))

    @property
    def can_auto_resolve(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("can_auto_resolve"))

    @property
    def semantic_impact(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("semantic_impact"))

    @property
    def risks(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("risks"))

    

class RelationshipInferenceAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RelationshipInference")
        self._properties: typing.Set[str] = set([ "id",  "type",  "source_id",  "target_id",  "source_type",  "target_type",  "properties",  "confidence_score", ])
        self._props = RelationshipInferenceProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RelationshipInferenceProperties":
        return self._props


class RelationshipInferenceViewer(RelationshipInferenceAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class RelationshipInferenceProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("id"))

    @property
    def type(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("type"))

    @property
    def source_id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("source_id"))

    @property
    def target_id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("target_id"))

    @property
    def source_type(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("source_type"))

    @property
    def target_type(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("target_type"))

    @property
    def properties(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("properties"))

    @property
    def confidence_score(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence_score"))

    

class RelationshipPropertyAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("RelationshipProperty")
        self._properties: typing.Set[str] = set([ "type",  "description",  "required", ])
        self._props = RelationshipPropertyProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "RelationshipPropertyProperties":
        return self._props


class RelationshipPropertyViewer(RelationshipPropertyAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class RelationshipPropertyProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def type(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("type"))

    @property
    def description(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def required(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("required"))

    

class ResolutionOptionAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ResolutionOption")
        self._properties: typing.Set[str] = set([ "id",  "description",  "resolution_type",  "resolution_data",  "confidence",  "reasoning", ])
        self._props = ResolutionOptionProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ResolutionOptionProperties":
        return self._props


class ResolutionOptionViewer(ResolutionOptionAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ResolutionOptionProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("id"))

    @property
    def description(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("description"))

    @property
    def resolution_type(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("resolution_type"))

    @property
    def resolution_data(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("resolution_data"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    @property
    def reasoning(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("reasoning"))

    

class ResolutionOptionsAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ResolutionOptions")
        self._properties: typing.Set[str] = set([ "options",  "recommended_option_id",  "recommendation_reasoning", ])
        self._props = ResolutionOptionsProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ResolutionOptionsProperties":
        return self._props


class ResolutionOptionsViewer(ResolutionOptionsAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ResolutionOptionsProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def options(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("options"))

    @property
    def recommended_option_id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("recommended_option_id"))

    @property
    def recommendation_reasoning(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("recommendation_reasoning"))

    

class ResolvedEntitiesAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ResolvedEntities")
        self._properties: typing.Set[str] = set([ "matching_ids",  "confidence_score",  "explanation", ])
        self._props = ResolvedEntitiesProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ResolvedEntitiesProperties":
        return self._props


class ResolvedEntitiesViewer(ResolvedEntitiesAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ResolvedEntitiesProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def matching_ids(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("matching_ids"))

    @property
    def confidence_score(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence_score"))

    @property
    def explanation(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("explanation"))

    

class SchemaGenerationResultAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("SchemaGenerationResult")
        self._properties: typing.Set[str] = set([ "generated_schema",  "confidence",  "suggestions",  "explanation", ])
        self._props = SchemaGenerationResultProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "SchemaGenerationResultProperties":
        return self._props


class SchemaGenerationResultViewer(SchemaGenerationResultAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class SchemaGenerationResultProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def generated_schema(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("generated_schema"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    @property
    def suggestions(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("suggestions"))

    @property
    def explanation(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("explanation"))

    

class SchemaRefinementResponseAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("SchemaRefinementResponse")
        self._properties: typing.Set[str] = set([ "refined_schema",  "changes_made",  "confidence",  "explanation", ])
        self._props = SchemaRefinementResponseProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "SchemaRefinementResponseProperties":
        return self._props


class SchemaRefinementResponseViewer(SchemaRefinementResponseAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class SchemaRefinementResponseProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def refined_schema(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("refined_schema"))

    @property
    def changes_made(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("changes_made"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    @property
    def explanation(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("explanation"))

    

class SelectedResolutionAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("SelectedResolution")
        self._properties: typing.Set[str] = set([ "option_id",  "resolution_type",  "resolution_data",  "confidence", ])
        self._props = SelectedResolutionProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "SelectedResolutionProperties":
        return self._props


class SelectedResolutionViewer(SelectedResolutionAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class SelectedResolutionProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def option_id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("option_id"))

    @property
    def resolution_type(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("resolution_type"))

    @property
    def resolution_data(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("resolution_data"))

    @property
    def confidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("confidence"))

    

class StandardisedPropertiesAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("StandardisedProperties")
        self._properties: typing.Set[str] = set([ "entity_id",  "properties", ])
        self._props = StandardisedPropertiesProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "StandardisedPropertiesProperties":
        return self._props


class StandardisedPropertiesViewer(StandardisedPropertiesAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class StandardisedPropertiesProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def entity_id(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("entity_id"))

    @property
    def properties(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("properties"))

    



class ResolutionStrategyAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ResolutionStrategy")
        self._values: typing.Set[str] = set([ "KEEP_STAGING",  "KEEP_PRODUCTION",  "MERGE_VALUES",  "KEEP_BOTH", ])
        self._vals = ResolutionStrategyValues(self._bldr, self._values)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ResolutionStrategyValues":
        return self._vals


class ResolutionStrategyViewer(ResolutionStrategyAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    def list_values(self) -> typing.List[typing.Tuple[str, EnumValueViewer]]:
        return [(name, EnumValueViewer(self._bldr.value(name))) for name in self._values]


class ResolutionStrategyValues:
    def __init__(self, enum_bldr: EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values

    

    @property
    def KEEP_STAGING(self) -> EnumValueViewer:
        return EnumValueViewer(self.__bldr.value("KEEP_STAGING"))
    

    @property
    def KEEP_PRODUCTION(self) -> EnumValueViewer:
        return EnumValueViewer(self.__bldr.value("KEEP_PRODUCTION"))
    

    @property
    def MERGE_VALUES(self) -> EnumValueViewer:
        return EnumValueViewer(self.__bldr.value("MERGE_VALUES"))
    

    @property
    def KEEP_BOTH(self) -> EnumValueViewer:
        return EnumValueViewer(self.__bldr.value("KEEP_BOTH"))
    

    


__all__ = ["TypeBuilder"]
